server:
  port: 8888
eureka:
  # 开启之前需要修改一下客户端设置（虽然是服务端
  client:
    # 由于我们是作为服务端角色，所以不需要获取服务端，改为false，默认为true;
    #改为false后不会把自己也注册到注册中心里面,后面做集群是可以的把自己注册到注册中心里面
    fetch-registry: false
    # 暂时不需要将自己也注册到Eureka
    register-with-eureka: false
    # 将eureka服务端指向自己
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.43.168:3306/test_spring_cloud
    #    zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: abC123456!